### ISSUE TITLE
Totally ignorable feature request: multiple templates in a repo

### ISSUE THREAD

**Issue by latentflip** [jaz303/template-anything#2]
Something I've been thinking about at &yet is having a project-templates repo, where we can store our canonical project templates. Now, obviously I could create a repo for every template. But I'm wondering if there's any way that ta could support multiple templates in a repo.

I don't know what that'd look like exactly, perhaps either:

`ta andyet/templates/some-specific-template foo`

or maybe the root could have a file/manifest to indicate that it's a multi-project thing, and the user could be prompted to select the template they want based on the dirs in the project root that have plan.tpl files?

I guess this is only really relevant to github installs too (if you have the templates on disk you can just point to any dir).

**Comment by jaz303** [comment]
In your example would `foo` be a directory within the repo?

Do you expect to share any files between the templates?

**Comment by latentflip** [comment]
Sorry no I meant that `some-specific-template` would be a directory within the repo. (this was a github example).

So andyet/templates is the repo, with some-specific-template as a dir with it's own plan.tpl, foo was where I was copying to.

And no, I wasn't thinking files would be shared, just that I could have a single github repo with lots of templates in it.

**Comment by jaz303** [comment]
D'oh yep I see now. I think that should be quite easy. Will look at it this afternoon.

**Comment by latentflip** [comment]
Please, no rush :) just whenever you were going to hack on it anyway :)

**Comment by jaz303** [comment]
To avoid ambiguity I think I'll implement this as a command line option, e.g.:

`ta jaz303/foobar -d subdir`

How does that sound?

**Comment by latentflip** [comment]
Yeah, that sounds good

On 4 December 2015 at 16:28, Jason Frame notifications@github.com wrote:

> To avoid ambiguity I think I'll implement this as a command line option,
> e.g.:
> 
> ta jaz303/foobar -d subdir
> 
> How does that sound?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jaz303/template-anything/issues/2#issuecomment-162012297
> .

## 

Philip Roberts
latentflip.com
